AWSTemplateFormatVersion: '2010-09-09'
Description: Single Page App for centivo csr portal
Resources:
  StaticContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  StaticContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticContentBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref StaticContentBucket, /*]]

  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - StaticContentBucket
    Properties:
      DistributionConfig:
        Comment: CDN for S3 site
        Enabled: true
        PriceClass: PriceClass_100
        Origins:
        - Id: S3Origin
          DomainName: !Select [2, !Split ["/", !GetAtt StaticContentBucket.WebsiteURL]]
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          MaxTTL: 120
          MinTTL: 0
          DefaultTTL: 120
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        CustomErrorResponses:
        - ErrorCode: '404'
          ResponsePagePath: '/index.html'
          ResponseCode: '200'
        - ErrorCode: '403'
          ResponsePagePath: '/index.html'
          ResponseCode: '200'

Outputs:
    BucketName:
        Description: Name of the S3 bucket to serve content
        Value: !Ref StaticContentBucket
    CloudfrontEndpoint:
        Description: Endpoint for Cloudfront distribution
        Value: !GetAtt WebsiteCDN.DomainName